### ISSUE TITLE
Container still running after I exit zoom

### ISSUE THREAD

**Issue by draghuram** [mdouchement/docker-zoom-us#3]
I just started using this container and tested it using Zoom's test meeting. It worked very nicely. Thanks.

However, I noticed that the container is still running after I existed the meeting and killed the window. Isn't it supposed to go away?

**Comment by jakommo** [comment]
I think this is a zoom issue rather than an issue with the container.
If I close the windows with the `x` in the menu bar, the window is closed, but the zoom process is still running and thus the container is not stopped.
When I click on the availability icon (green icon next to my name) and choose `exit` in the menu, the process is shutdown and the container is stopped. 
AFAIK `x` only minimizes to tray instead of really closing the application. At least that's the behavior if I run zoom without the container.

**Comment by draghuram** [comment]
I verified that this indeed is the issue. Thanks.
